export type {
  HeroContent,
  HeroFieldAdmin,
  HeroContentAdmin,
  HeroUpdate,
  BodyContent,
  BodyContentAdmin,
  BodyUpdate,
  FooterAboutContent,
  FooterAboutContentAdmin,
  FooterAboutUpdate,
  ContactInfo,
  ContactInfoAdmin,
  ContactInfoUpdate,
  ResourceLink,
  ResourceLinkAdmin,
  ResourceLinkCreate,
  ResourceLinkUpdate,
  ResourceReorder,
  FooterContent,
  FooterContentAdmin,
  EditorialPublicResponse,
  EditorialAdminResponse,
} from '../../../../packages/shared/types/editorial'
